### ISSUE TITLE
git clone issue 

### ISSUE THREAD

**Issue by johnson1484** [initialstate/smart-scale#9]
hello my senior team and I ran the git clone with your http: and it couldn't find it. We get an error saying 
"cloning into 'smart-scale'
ssh: Could not resolve hostname https: name or service not known 
fatal: Could not read remote repository.

Please make sure you have the correct access rights 
and the repository exists."

we tried  Stavros Korokithakis' script while using your directions and it worked as intended. just want to know how to fix the issue we are getting with your https: .

**Comment by jrbail01** [comment]
I am not seeing a problem cloning. Here is a log from a test I just did (make sure you are using the command `git clone https://github.com/initialstate/smart-scale.git`)

jamies-air:tmp jamesbailey$ **git clone https://github.com/initialstate/smart-scale.git**
Cloning into 'smart-scale'...
remote: Enumerating objects: 44, done.
remote: Total 44 (delta 0), reused 0 (delta 0), pack-reused 44
Unpacking objects: 100% (44/44), done.
jamies-air:tmp jamesbailey$ ls
smart-scale
jamies-air:tmp jamesbailey$ ls smart-scale/
PlayButton.jpg		Smartscaleplay.png	wiiboard_test.py
README.md		smartscale.py
